"""S2.5 — ``POST /chat``, streamed as Server-Sent Events (decisions D20-D23).

One route, one envelope. The stream is ``stage``* → exactly one ``result`` → ``done``: the
stage frames are advisory progress the interface may show in the customer's words, and the
single result frame is the answer. A refusal is a **result** with ``display: "unsupported"``
— never an ``error`` frame — because the service did its job when it declined to invent a
number (D23). A follow-up rides the same frame as ``display: "follow_up"``.

The stage enum is translated from the graph's node names rather than being them, so
renaming a node cannot change user-visible text. Starlette's ``StreamingResponse`` is
enough for SSE; ``sse-starlette`` would be a dependency for six lines of formatting.

The path is ``/chat``, not ``/api/chat``: nginx strips the prefix on the way through.
"""

from __future__ import annotations

import json
import logging
from collections.abc import AsyncIterator
from typing import Any, Literal, cast

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from langchain_core.messages import AIMessage, HumanMessage
from langchain_core.runnables import RunnableConfig
from pydantic import BaseModel, Field

from logistics_analytics.agent.graph import ANSWER_NODE, CLASSIFY_NODE, ENFORCE_NODE, ChatGraph

logger = logging.getLogger(__name__)

#: The closed stage enum (D23b), hand-extended with ``forecasting`` for Slice 3 (spec
#: review Q3). Advisory only — an interface that ignores them still works.
Stage = Literal["interpreting", "querying", "forecasting", "composing"]

#: Which stage each of our node updates announces. ``enforce`` announces nothing: the
#: result frame follows it immediately, and a stage line nobody sees is noise.
STAGE_AFTER_NODE: dict[str, Stage] = {CLASSIFY_NODE: "querying", ANSWER_NODE: "composing"}

#: What the customer is told when the service itself failed. Deliberately number-free.
FAULT_MESSAGE = (
    "I couldn't get you an answer this time. Something went wrong while counting, so there "
    "is nothing to show you - better that than a figure I am not sure about."
)


class ChatRequest(BaseModel):
    """One question, and the conversation it belongs to.

    ``conversation_id`` is generated by the client and becomes the checkpointer's
    ``thread_id``. That is what lets a reply to a follow-up re-enter the graph with the
    earlier turn still in view (agent-design rule 7) while the route itself stays stateless.
    """

    question: str = Field(min_length=1, max_length=1000)
    conversation_id: str = Field(min_length=1, max_length=128)


class ChatExplanation(BaseModel):
    """The query that produced the answer, echoed back (requirement 2.4).

    Field for field the dashboard's ``ChartParams`` plus ``row_count``, so the front-end's
    data table and explainability panel read a chat answer with no new type.
    """

    metrics: list[str]
    group_by: str
    filters: dict[str, str]
    order: str
    row_count: int


class ChatStat(BaseModel):
    """The single figure a stat answer prints. ``None`` whenever there is a chart instead."""

    metric: str
    value: float | int


class ChatFollowUp(BaseModel):
    """The structured question asked when one required parameter is genuinely missing."""

    missing_info: str
    question: str
    options: list[str]


class ChatForecast(BaseModel):
    """The typed forecast block of a ``forecast_line`` answer (Slice 3, decision D27).

    Typed rather than fished out of prose so the card renders the recommendation and the
    methodology from fields, and the digit checks treat them as evidence. ``total`` is the
    sum of the projected values; ``recommended_stock`` is that total plus the safety
    buffer, in whole units.
    """

    sku: str
    horizon: int
    window: int
    total: float
    recommended_stock: int
    buffer_pct: float
    methodology: str


class ChatResult(BaseModel):
    """The one result frame. Every legal answer is this shape, refusals included.

    Validating the graph's envelope against this model before it reaches the wire is a real
    gate rather than ceremony: the envelope is assembled from a tool's JSON, so a tool that
    changed its shape would otherwise reach the browser unnoticed.
    """

    answer: str
    display: Literal["stat", "line", "bar", "stacked", "unsupported", "follow_up", "forecast_line"]
    data: ChatStat | None
    rows: list[dict[str, str | float | int | None]]
    explanation: ChatExplanation | None
    follow_up: ChatFollowUp | None
    forecast: ChatForecast | None = None


def create_chat_router(chat_graph: ChatGraph) -> APIRouter:
    """Build the chat route around an injected graph, like every other router here."""
    router = APIRouter(tags=["chat"])

    @router.post(
        "/chat",
        summary="Ask a question in natural language; answered as a Server-Sent Event stream",
    )
    async def ask(request: ChatRequest) -> StreamingResponse:
        """Stream one answer.

        ``no-cache`` and ``X-Accel-Buffering: no`` are what make the progress frames arrive
        as progress: without them nginx buffers the whole response and the customer sees
        nothing until the answer is already complete.
        """
        return StreamingResponse(
            _stream(chat_graph, request),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
        )

    return router


def _frame(event: str, data: dict[str, Any]) -> str:
    """One SSE frame. The blank line is the delimiter, so it is not cosmetic."""
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


async def _stream(chat_graph: ChatGraph, request: ChatRequest) -> AsyncIterator[str]:
    """Run the graph and turn its node updates into frames as they happen.

    The stage frames are yielded from inside the graph's own update loop rather than
    collected and replayed at the end — a progress line that arrives with the answer is not
    progress.

    The run is guarded because a stream cannot report a failure with a status code: the
    response has already begun and its status is already 200. A fault therefore ends the
    way every other turn ends, with a frame the interface can render, and the traceback
    goes to the log where it belongs.
    """
    yield _frame("stage", {"stage": "interpreting"})
    config: RunnableConfig = {"configurable": {"thread_id": request.conversation_id}}
    envelope: dict[str, Any] | None = None
    result: ChatResult | None = None

    try:
        async for item in chat_graph.astream(
            {"messages": [HumanMessage(content=request.question)]},
            config=config,
            # Two modes, so the frames become tuples. ``custom`` carries the forecast
            # tool's mid-run stage event, which no node update can announce because the
            # tool runs *inside* the answer node (D29). ``subgraphs=True`` is what lets
            # that event out at all — the tool executes in ``create_agent``'s inner graph,
            # and without it the parent stream swallows the chunk (measured, not read).
            # Node names are still never inspected: subgraph updates are skipped whole.
            stream_mode=["updates", "custom"],
            subgraphs=True,
        ):
            # ``astream`` is typed as yielding dicts OR tuples; with a mode list and
            # ``subgraphs`` it is always (namespace, mode, chunk), which mypy cannot know
            # without the cast.
            namespace, mode, chunk = cast("tuple[tuple[str, ...], str, Any]", item)
            if mode == "custom":
                custom_stage = chunk.get("stage") if isinstance(chunk, dict) else None
                if isinstance(custom_stage, str):
                    yield _frame("stage", {"stage": custom_stage})
                continue
            if namespace:
                continue
            for node, payload in chunk.items():
                stage = STAGE_AFTER_NODE.get(node)
                if stage is not None and (node != CLASSIFY_NODE or payload.get("is_allowed")):
                    yield _frame("stage", {"stage": stage})
                if node == ENFORCE_NODE:
                    envelope = _envelope_of(payload)
        if envelope is None:
            message = "the graph finished without producing an answer envelope"
            raise RuntimeError(message)
        result = ChatResult.model_validate(envelope)
    except Exception:
        logger.exception("chat turn failed for conversation %s", request.conversation_id)
        yield _frame("error", {"message": FAULT_MESSAGE})
    else:
        yield _frame("result", result.model_dump(mode="json"))

    yield _frame("done", {})


def _envelope_of(payload: dict[str, Any]) -> dict[str, Any] | None:
    """Pull the answer envelope off the message the enforce node appended."""
    messages = payload.get("messages") or []
    for message in messages:
        if isinstance(message, AIMessage):
            envelope = message.additional_kwargs.get("envelope")
            if isinstance(envelope, dict):
                return envelope
    return None
